# Stage 0, "build-stage", based on Bun, to build and compile the frontend
FROM docker.1ms.run/oven/bun:1 AS build-stage

WORKDIR /app

COPY package.json /app/

RUN bun install --registry https://registry.npmmirror.com

COPY . /app/
ARG VITE_API_URL

RUN bun run build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM docker.1ms.run/nginx:1

COPY --from=build-stage /app/dist/ /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx-backend-not-found.conf /etc/nginx/extra-conf.d/backend-not-found.conf
